#ifndef VK_WRAPPER_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO_HPP
#define VK_WRAPPER_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO_HPP

#include <vulkan/vulkan.h>

VkPipelineVertexInputStateCreateInfo GeneratePipelineVertexInputStateCreateInfo();

#endif // VK_WRAPPER_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO_HPP
