#ifndef VK_WRAPPER_PARAMETER_INFOS_HPP
#define VK_WRAPPER_PARAMETER_INFOS_HPP

#include "VulkanHelpers/ParameterInfos/AcquireNextImageInfo.hpp"
#include "VulkanHelpers/ParameterInfos/ApplicationInfo.hpp"
#include "VulkanHelpers/ParameterInfos/BindBufferMemoryInfo.hpp"
#include "VulkanHelpers/ParameterInfos/BindDescriptorSetsInfo.hpp"
#include "VulkanHelpers/ParameterInfos/BindImageMemoryInfo.hpp"
#include "VulkanHelpers/ParameterInfos/BufferMemoryRequirementsInfo.hpp"
#include "VulkanHelpers/ParameterInfos/CommandBufferAllocateInfo.hpp"
#include "VulkanHelpers/ParameterInfos/CommandBufferBeginInfo.hpp"
#include "VulkanHelpers/ParameterInfos/CommandBufferSubmitInfo.hpp"
#include "VulkanHelpers/ParameterInfos/CopyBufferInfo.hpp"
#include "VulkanHelpers/ParameterInfos/CopyBufferToImageInfo.hpp"
#include "VulkanHelpers/ParameterInfos/DependencyInfo.hpp"
#include "VulkanHelpers/ParameterInfos/DescriptorBufferInfo.hpp"
#include "VulkanHelpers/ParameterInfos/DescriptorSetAllocateInfo.hpp"
#include "VulkanHelpers/ParameterInfos/DeviceQueueInfo.hpp"
#include "VulkanHelpers/ParameterInfos/ImageMemoryRequirementsInfo.hpp"
#include "VulkanHelpers/ParameterInfos/MemoryAllocateInfo.hpp"
#include "VulkanHelpers/ParameterInfos/MemoryMapInfo.hpp"
#include "VulkanHelpers/ParameterInfos/MemoryUnmapInfo.hpp"
#include "VulkanHelpers/ParameterInfos/PhysicalDeviceSurfaceInfo.hpp"
#include "VulkanHelpers/ParameterInfos/PresentInfo.hpp"
#include "VulkanHelpers/ParameterInfos/RenderPassBeginInfo.hpp" 
#include "VulkanHelpers/ParameterInfos/SemaphoreSubmitInfo.hpp"
#include "VulkanHelpers/ParameterInfos/SubmitInfo.hpp"
#include "VulkanHelpers/ParameterInfos/SubpassBeginInfo.hpp"
#include "VulkanHelpers/ParameterInfos/SubpassEndInfo.hpp"

#endif // VK_WRAPPER_PARAMETER_INFOS_HPP
