#ifndef VK_WRAPPER_PARAMETER_STRUCTS_HPP
#define VK_WRAPPER_PARAMETER_STRUCTS_HPP

#include "VulkanHelpers/ParameterStructs/AttachmentDescription.hpp"
#include "VulkanHelpers/ParameterStructs/AttachmentReference.hpp"
#include "VulkanHelpers/ParameterStructs/BufferCopy.hpp"
#include "VulkanHelpers/ParameterStructs/BufferImageCopy.hpp"
#include "VulkanHelpers/ParameterStructs/ClearValue.hpp"
#include "VulkanHelpers/ParameterStructs/DescriptorPoolSize.hpp"
#include "VulkanHelpers/ParameterStructs/DescriptorSetLayoutBinding.hpp"
#include "VulkanHelpers/ParameterStructs/ExtensionProperties.hpp"
#include "VulkanHelpers/ParameterStructs/ImageMemoryBarrier.hpp"
#include "VulkanHelpers/ParameterStructs/LayerProperties.hpp"
#include "VulkanHelpers/ParameterStructs/PhysicalDeviceFeatures.hpp"
#include "VulkanHelpers/ParameterStructs/PhysicalDeviceLimits.hpp"
#include "VulkanHelpers/ParameterStructs/PhysicalDeviceProperties.hpp"
#include "VulkanHelpers/ParameterStructs/PhysicalDeviceSparseProperties.hpp"
#include "VulkanHelpers/ParameterStructs/PhysicalDeviceSynchronization2Features.hpp"
#include "VulkanHelpers/ParameterStructs/PipelineColorBlendAttachmentState.hpp"
#include "VulkanHelpers/ParameterStructs/QueueFamilyProperties.hpp"
#include "VulkanHelpers/ParameterStructs/Rect2D.hpp"
#include "VulkanHelpers/ParameterStructs/SubpassDependency.hpp"
#include "VulkanHelpers/ParameterStructs/SubpassDescription.hpp"
#include "VulkanHelpers/ParameterStructs/SurfaceCapabilities.hpp"
#include "VulkanHelpers/ParameterStructs/SurfaceFormat.hpp"
#include "VulkanHelpers/ParameterStructs/Version.hpp"
#include "VulkanHelpers/ParameterStructs/VertexInputAttributeDescription.hpp"
#include "VulkanHelpers/ParameterStructs/VertexInputBindingDescription.hpp"
#include "VulkanHelpers/ParameterStructs/Viewport.hpp"
#include "VulkanHelpers/ParameterStructs/WriteDescriptorSet.hpp"

#endif // VK_WRAPPER_PARAMETER_STRUCTS_HPP
